# Generated by Django 5.2.8 on 2025-11-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaPDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombrePDP', models.CharField(max_length=200)),
                ('CedulaPDP', models.TextField()),
                ('SerialPDP', models.CharField(default='New', max_length=50)),
                ('sharepoint_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
    ]
